export const DISCIPLINES = [
  'Product Design',
  'Graphic Design',
  'Illustration',
  'Motion Design',
  'UX Design',
  'UI Design',
  '3D Design',
  'Architecture',
  'Photography',
  'Art Direction',
  'Branding',
  'Animation',
  'Interaction Design',
  'Concept Art',
] as const

export const EXPERIENCE_LEVELS = [
  { value: 'student', label: 'Student' },
  { value: 'junior', label: 'Junior (0-2 years)' },
  { value: 'mid', label: 'Mid-level (2-5 years)' },
  { value: 'senior', label: 'Senior (5+ years)' },
] as const

export const SOFTWARE_TOOLS = [
  'Figma',
  'Adobe XD',
  'Sketch',
  'Adobe Photoshop',
  'Adobe Illustrator',
  'Adobe InDesign',
  'Adobe After Effects',
  'Cinema 4D',
  'Blender',
  'Maya',
  'AutoCAD',
  'Revit',
  'Procreate',
  'Fresco',
  'CorelDRAW',
  'Affinity Designer',
  'Affinity Photo',
  'Affinity Publisher',
  'Pixelmator Pro',
  'GIMP',
  'Krita',
  'Clip Studio Paint',
  'Rebelle',
  'Substance Painter',
  'ZBrush',
  'Houdini',
  'TouchDesigner',
  'Processing',
  'p5.js',
  'Three.js',
  'Unreal Engine',
  'Unity',
] as const

export const NOTIFICATION_CATEGORIES = [
  'Activity on work',
  'Comments and replies',
  'Follows and appreciations',
  'Messages',
  'Opportunities',
  'Updates from followed users',
  'Digest summaries',
] as const

export const SETTINGS_SECTIONS = [
  { id: 'profile', label: 'Profile', icon: 'user' },
  { id: 'identity', label: 'Creative Identity', icon: 'palette' },
  { id: 'account', label: 'Account & Security', icon: 'lock' },
  { id: 'notifications', label: 'Notifications', icon: 'bell' },
  { id: 'privacy', label: 'Privacy & Visibility', icon: 'eye' },
  { id: 'feed', label: 'Feed & Discovery', icon: 'compass' },
  { id: 'appearance', label: 'Appearance', icon: 'sun' },
  { id: 'credits', label: 'Credits & Reputation', icon: 'award' },
  { id: 'connections', label: 'Connections', icon: 'link' },
  { id: 'data', label: 'Data & Export', icon: 'download' },
] as const
